/**
 * Fixture payloads for the credential-free design preview at
 * `/proto/alerts-preview`.
 *
 * ⛔ THIS IS APP CODE, NOT TEST CODE. `src/test/fixtures.ts` builds the same
 * shapes and is deliberately NOT imported here: it reaches into `~/test/contract`,
 * which reads the OpenAPI document off `node:fs`, and a preview route that pulled
 * that into the browser bundle would be a build failure with a very long
 * explanation. The literals below are standalone and typed against `~/api/types`
 * exactly as the test builders are, so a contract change that adds a required
 * field breaks this file at `tsc --noEmit` rather than producing a preview of a
 * screen the server can never render.
 *
 * ⭐ EVERY VALUE IS A LITERAL. No `Date.now()`, no randomness — two people
 * reviewing the same design are looking at the same thirty rows, and a
 * screenshot taken today can be compared with one taken next week.
 *
 * The spread is chosen to make the design answer for itself: every lifecycle
 * state, both acknowledgement states, the three common severities plus an
 * operator-invented one and an absent one, snoozed rows, rows with no namespace
 * and no service, and alert names long enough to force the name column to
 * truncate.
 */
import type {
  Alert,
  AlertDetail,
  AlertEvent,
  AlertRollup,
  Cluster,
  Enrichment,
  LabelNameRow,
  Notification,
  Case,
  RuleHistory,
  RuleSnapshot,
  Snooze,
  SnoozeHistoryEntry,
} from "~/api/types";

/* -------------------------------------------------------------------------- */
/* The clock                                                                  */
/* -------------------------------------------------------------------------- */

/** "Now", as far as this preview is concerned. */
const NOW = "2026-08-16T12:00:00.000Z";
const MIN_2 = "2026-08-16T11:58:00.000Z";
const MIN_9 = "2026-08-16T11:51:00.000Z";
const MIN_21 = "2026-08-16T11:39:00.000Z";
const MIN_47 = "2026-08-16T11:13:00.000Z";
const HOUR_2 = "2026-08-16T10:02:00.000Z";
const HOUR_5 = "2026-08-16T07:14:00.000Z";
const HOUR_9 = "2026-08-16T03:26:00.000Z";
const HOUR_19 = "2026-08-15T17:31:00.000Z";
const DAY_2 = "2026-08-14T09:12:00.000Z";
const DAY_4 = "2026-08-12T22:48:00.000Z";
const DAY_8 = "2026-08-08T06:05:00.000Z";
const DAY_16 = "2026-07-31T14:20:00.000Z";
const DAY_40 = "2026-07-07T08:00:00.000Z";
const DAY_95 = "2026-05-13T08:00:00.000Z";

/* -------------------------------------------------------------------------- */
/* Rule snapshots                                                             */
/* -------------------------------------------------------------------------- */

const RULE_ERRORS = "1c9d3f4a-2b5e-4c7d-8e9f-0a1b2c3d4e01";
const RULE_LATENCY = "1c9d3f4a-2b5e-4c7d-8e9f-0a1b2c3d4e02";
const RULE_CRASHLOOP = "1c9d3f4a-2b5e-4c7d-8e9f-0a1b2c3d4e03";

const SOURCE_ID = "2d8e4a5b-3c6f-4d8e-9f0a-1b2c3d4e5f60";

function snapshot(patch: Partial<RuleSnapshot>): RuleSnapshot {
  return {
    id: RULE_ERRORS,
    source_id: SOURCE_ID,
    rule_fingerprint: "sha256:0f3c9a71b2d84e56",
    rule_file: "/etc/prometheus/rules/api-slo.yaml",
    rule_group: "api-slo",
    rule_name: "HighErrorRate",
    expr: 'sum(rate(http_requests_total{status=~"5.."}[5m])) by (service)\n  / sum(rate(http_requests_total[5m])) by (service) > 0.05',
    for_seconds: 900,
    keep_firing_for_seconds: 0,
    rule_labels: { severity: "critical", team: "payments" },
    rule_annotations: {
      summary: "Error rate above 5% for 15 minutes",
      runbook_url: "https://runbooks.example.com/high-error-rate",
    },
    origin: "prometheus_api",
    match_confidence: "exact",
    candidate_count: 1,
    captured_at: DAY_40,
    ...patch,
  };
}

/**
 * The snapshots the list's Rule column resolves against.
 *
 * Content addressing is why this map is three entries and not thirty: a page of
 * alerts firing under one unchanged rule shares one id.
 */
export const PREVIEW_RULE_SNAPSHOTS: ReadonlyMap<string, RuleSnapshot> = new Map<
  string,
  RuleSnapshot
>([
  [RULE_ERRORS, snapshot({})],
  [
    RULE_LATENCY,
    snapshot({
      id: RULE_LATENCY,
      rule_fingerprint: "sha256:77ab21c0de934f18",
      rule_group: "latency-slo",
      rule_name: "CheckoutLatencyP99Degraded",
      expr: 'histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{service="checkout-api"}[5m])) by (le)) > 1.5',
      for_seconds: 600,
      rule_labels: { severity: "warning", team: "checkout" },
      captured_at: DAY_16,
    }),
  ],
  [
    RULE_CRASHLOOP,
    snapshot({
      id: RULE_CRASHLOOP,
      rule_fingerprint: "sha256:c41e08b6a5f27d93",
      rule_file: "/etc/prometheus/rules/kubernetes.yaml",
      rule_group: "kubernetes-apps",
      rule_name: "KubePodCrashLooping",
      expr: 'increase(kube_pod_container_status_restarts_total[10m]) > 3',
      for_seconds: 300,
      keep_firing_for_seconds: 300,
      rule_labels: { severity: "warning" },
      rule_annotations: { summary: "Pod is restarting repeatedly" },
      match_confidence: "probable",
      candidate_count: 2,
      captured_at: DAY_8,
    }),
  ],
]);

/* -------------------------------------------------------------------------- */
/* Snoozes                                                                    */
/* -------------------------------------------------------------------------- */

function snoozeUntil(patch: Partial<Snooze>): Snooze {
  return {
    id: "9d4e0a1b-8c2f-4d5e-6a7b-8c9d0e1f2a01",
    snoozed_at: MIN_47,
    snoozed_until: "2026-08-16T14:30:00.000Z",
    snoozed_by_label: "priya@example.com",
    note: "deploy window, expected until 14:30",
    ...patch,
  };
}

/* -------------------------------------------------------------------------- */
/* Alerts                                                                     */
/* -------------------------------------------------------------------------- */

const BASE: Alert = {
  id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d3800",
  alert_key: "b3f1c2d4e5a60700",
  source_fingerprint: "9a8b7c6d5e4f3000",
  alertname: "HighErrorRate",
  severity: "critical",
  namespace: "payments",
  service: "checkout-api",
  cluster_key: "prod-eu",
  labels: {
    alertname: "HighErrorRate",
    severity: "critical",
    namespace: "payments",
    service: "checkout-api",
    pod: "checkout-api-7d9f4b6c8-x2m4q",
    team: "payments",
  },
  annotations: { summary: "Error rate above 5% for 15 minutes" },
  state: "firing",
  first_seen_at: DAY_2,
  last_seen_at: MIN_2,
  last_state_change_at: MIN_21,
  total_cases: 3,
  flap_score: 0,
  is_flapping: false,
  synthetic: false,
  snooze: null,
  rule: { id: RULE_ERRORS },
};

function mk(patch: Partial<Alert>): Alert {
  return { ...BASE, ...patch };
}

/**
 * Thirty rows, ordered newest-activity-first exactly as the default sort would
 * hand them over, so the preview's scroll behaves like the real screen's.
 */
export const PREVIEW_ALERTS: readonly Alert[] = [
  mk({
    id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d3801",
    alert_key: "b3f1c2d4e5a60701",
    alertname: "KubernetesStatefulSetReplicasMismatchForExtendedPeriod",
    severity: "critical",
    namespace: "payments",
    service: "ledger-writer",
    labels: {
      alertname: "KubernetesStatefulSetReplicasMismatchForExtendedPeriod",
      severity: "critical",
      namespace: "payments",
      service: "ledger-writer",
      statefulset: "ledger-writer",
      team: "payments",
    },
    annotations: { summary: "2 of 5 replicas have been unavailable for 40 minutes" },
    is_flapping: true,
    flap_score: 7.4,
    total_cases: 19,
    first_seen_at: DAY_16,
    last_seen_at: NOW,
    last_state_change_at: MIN_9,
    rule: null,
    current_case: {
      id: "0f8fad5b-d9cb-469f-a165-708677289504",
      alert_id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d3801",
      seq: 19,
      state: "open",
      ack_state: "unacked",
      started_at: MIN_9,
      last_observed_at: NOW,
      source_starts_at: MIN_9,
      observed_skew_ms: 180,
    },
  }),
  mk({
    id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d3802",
    alert_key: "b3f1c2d4e5a60702",
    alertname: "HighErrorRate",
    last_seen_at: MIN_2,
    total_cases: 4,
    current_case: {
      id: "0f8fad5b-d9cb-469f-a165-708677289505",
      alert_id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d3802",
      seq: 4,
      state: "open",
      ack_state: "unacked",
      started_at: MIN_21,
      last_observed_at: MIN_2,
      source_starts_at: MIN_21,
      observed_skew_ms: 60,
    },
  }),
  mk({
    id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d3803",
    alert_key: "b3f1c2d4e5a60703",
    alertname: "PaymentAuthorisationGatewayCircuitBreakerOpenForMoreThanFiveMinutes",
    severity: "critical",
    namespace: "payments",
    service: "auth-gateway",
    labels: {
      alertname: "PaymentAuthorisationGatewayCircuitBreakerOpenForMoreThanFiveMinutes",
      severity: "critical",
      namespace: "payments",
      service: "auth-gateway",
      provider: "stripe",
      team: "payments",
    },
    annotations: { summary: "Circuit breaker open — every authorisation is failing fast" },
    last_seen_at: MIN_2,
    last_state_change_at: MIN_47,
    total_cases: 2,
    current_case: {
      id: "0f8fad5b-d9cb-469f-a165-708677289506",
      alert_id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d3803",
      seq: 2,
      state: "open",
      ack_state: "acked",
      started_at: MIN_47,
      last_observed_at: MIN_2,
      source_starts_at: MIN_47,
      observed_skew_ms: 90,
    },
  }),
  mk({
    id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d3804",
    alert_key: "b3f1c2d4e5a60704",
    alertname: "CheckoutLatencyP99Degraded",
    severity: "warning",
    namespace: "checkout",
    service: "checkout-api",
    labels: {
      alertname: "CheckoutLatencyP99Degraded",
      severity: "warning",
      namespace: "checkout",
      service: "checkout-api",
      route: "/v2/orders",
    },
    annotations: { summary: "p99 above 1.5s for 10 minutes" },
    snooze: snoozeUntil({}),
    last_seen_at: MIN_9,
    last_state_change_at: HOUR_2,
    total_cases: 6,
    rule: { id: RULE_LATENCY },
    current_case: {
      id: "0f8fad5b-d9cb-469f-a165-708677289507",
      alert_id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d3804",
      seq: 6,
      state: "open",
      ack_state: "unacked",
      started_at: HOUR_2,
      last_observed_at: MIN_9,
      source_starts_at: HOUR_2,
      observed_skew_ms: 140,
    },
  }),
  mk({
    id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d3805",
    alert_key: "b3f1c2d4e5a60705",
    alertname: "KubePodCrashLooping",
    severity: "warning",
    namespace: "search",
    service: "indexer",
    labels: {
      alertname: "KubePodCrashLooping",
      severity: "warning",
      namespace: "search",
      service: "indexer",
      pod: "indexer-6c4d8f9b7a-lm2xz",
      container: "indexer",
    },
    annotations: { summary: "Pod restarted 6 times in 10 minutes" },
    is_flapping: true,
    flap_score: 11.8,
    last_seen_at: MIN_9,
    last_state_change_at: MIN_9,
    total_cases: 214,
    first_seen_at: DAY_40,
    rule: { id: RULE_CRASHLOOP },
    current_case: {
      id: "0f8fad5b-d9cb-469f-a165-708677289508",
      alert_id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d3805",
      seq: 214,
      state: "open",
      ack_state: "unacked",
      started_at: MIN_9,
      last_observed_at: MIN_9,
      source_starts_at: MIN_9,
      observed_skew_ms: 210,
    },
  }),
  mk({
    id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d3806",
    alert_key: "b3f1c2d4e5a60706",
    alertname: "CertificateExpiringSoon",
    severity: "info",
    namespace: null,
    service: null,
    labels: {
      alertname: "CertificateExpiringSoon",
      severity: "info",
      domain: "api.example.com",
      issuer: "letsencrypt",
    },
    annotations: { summary: "TLS certificate expires in 9 days" },
    last_seen_at: MIN_21,
    last_state_change_at: DAY_2,
    first_seen_at: DAY_2,
    total_cases: 1,
    rule: null,
    current_case: {
      id: "0f8fad5b-d9cb-469f-a165-708677289509",
      alert_id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d3806",
      seq: 1,
      state: "open",
      ack_state: "unacked",
      started_at: DAY_2,
      last_observed_at: MIN_21,
      source_starts_at: DAY_2,
      observed_skew_ms: 40,
    },
  }),
  mk({
    id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d3807",
    alert_key: "b3f1c2d4e5a60707",
    alertname: "ReplicationLagAboveThreshold",
    severity: "sev1",
    namespace: "data",
    service: "postgres-primary",
    labels: {
      alertname: "ReplicationLagAboveThreshold",
      severity: "sev1",
      namespace: "data",
      service: "postgres-primary",
      replica: "pg-replica-3",
    },
    annotations: { summary: "Replica pg-replica-3 is 412 seconds behind" },
    last_seen_at: MIN_21,
    last_state_change_at: HOUR_5,
    total_cases: 8,
    rule: null,
    current_case: {
      id: "0f8fad5b-d9cb-469f-a165-708677289510",
      alert_id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d3807",
      seq: 8,
      state: "open",
      ack_state: "unacked",
      started_at: HOUR_5,
      last_observed_at: MIN_21,
      source_starts_at: HOUR_5,
      observed_skew_ms: 250,
    },
  }),
  mk({
    id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d3808",
    alert_key: "b3f1c2d4e5a60708",
    alertname: "UnlabelledScrapeTargetDown",
    severity: null,
    namespace: null,
    service: null,
    cluster_key: "prod-us",
    labels: { alertname: "UnlabelledScrapeTargetDown", instance: "10.42.7.19:9100" },
    annotations: {},
    last_seen_at: MIN_47,
    last_state_change_at: MIN_47,
    first_seen_at: MIN_47,
    total_cases: 1,
    rule: null,
    current_case: {
      id: "0f8fad5b-d9cb-469f-a165-708677289511",
      alert_id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d3808",
      seq: 1,
      state: "open",
      ack_state: "unacked",
      started_at: MIN_47,
      last_observed_at: MIN_47,
      source_starts_at: MIN_47,
      observed_skew_ms: 15,
    },
  }),
  mk({
    id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d3809",
    alert_key: "b3f1c2d4e5a60709",
    alertname: "DiskWillFillIn4Hours",
    severity: "critical",
    namespace: "infra",
    service: "node-exporter",
    cluster_key: "prod-us",
    labels: {
      alertname: "DiskWillFillIn4Hours",
      severity: "critical",
      namespace: "infra",
      service: "node-exporter",
      device: "/dev/nvme0n1p1",
      instance: "node-14",
    },
    annotations: { summary: "Projected to reach 100% at 16:10" },
    snooze: snoozeUntil({
      id: "9d4e0a1b-8c2f-4d5e-6a7b-8c9d0e1f2a02",
      snoozed_by_label: "dana@example.com",
      snoozed_until: "2026-08-16T18:00:00.000Z",
      note: "disk expansion scheduled",
    }),
    last_seen_at: MIN_47,
    last_state_change_at: HOUR_2,
    total_cases: 2,
    rule: null,
    current_case: {
      id: "0f8fad5b-d9cb-469f-a165-708677289512",
      alert_id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d3809",
      seq: 2,
      state: "open",
      ack_state: "acked",
      started_at: HOUR_2,
      last_observed_at: MIN_47,
      source_starts_at: HOUR_2,
      observed_skew_ms: 130,
    },
  }),
  mk({
    id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d380a",
    alert_key: "b3f1c2d4e5a6070a",
    alertname: "AlertmanagerConfigInconsistentAcrossReplicaSetMembers",
    severity: "warning",
    namespace: "monitoring",
    service: "alertmanager",
    state: "suppressed",
    labels: {
      alertname: "AlertmanagerConfigInconsistentAcrossReplicaSetMembers",
      severity: "warning",
      namespace: "monitoring",
      service: "alertmanager",
    },
    annotations: { summary: "Two of three members disagree on the routing tree" },
    last_seen_at: HOUR_2,
    last_state_change_at: HOUR_2,
    total_cases: 3,
    rule: null,
    current_case: {
      id: "0f8fad5b-d9cb-469f-a165-708677289513",
      alert_id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d380a",
      seq: 3,
      state: "open",
      ack_state: "unacked",
      started_at: HOUR_2,
      last_observed_at: HOUR_2,
      source_starts_at: HOUR_2,
      observed_skew_ms: 70,
    },
  }),
  mk({
    id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d380b",
    alert_key: "b3f1c2d4e5a6070b",
    alertname: "QueueDepthGrowing",
    severity: "warning",
    namespace: "notifications",
    service: "fanout-worker",
    state: "suppressed",
    labels: {
      alertname: "QueueDepthGrowing",
      severity: "warning",
      namespace: "notifications",
      service: "fanout-worker",
      queue: "email.outbound",
    },
    annotations: { summary: "Depth 84,000 and rising for 25 minutes" },
    last_seen_at: HOUR_2,
    last_state_change_at: HOUR_5,
    total_cases: 12,
    rule: null,
    current_case: {
      id: "0f8fad5b-d9cb-469f-a165-708677289514",
      alert_id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d380b",
      seq: 12,
      state: "open",
      ack_state: "acked",
      started_at: HOUR_5,
      last_observed_at: HOUR_2,
      source_starts_at: HOUR_5,
      observed_skew_ms: 310,
    },
  }),
  mk({
    id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d380c",
    alert_key: "b3f1c2d4e5a6070c",
    alertname: "HighErrorRate",
    namespace: "search",
    service: "query-api",
    cluster_key: "prod-us",
    labels: {
      alertname: "HighErrorRate",
      severity: "critical",
      namespace: "search",
      service: "query-api",
      pod: "query-api-58c7d9f4b6-qq81t",
    },
    annotations: { summary: "Error rate above 5% for 15 minutes" },
    last_seen_at: HOUR_2,
    last_state_change_at: HOUR_5,
    total_cases: 7,
  }),
  mk({
    id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d380d",
    alert_key: "b3f1c2d4e5a6070d",
    alertname: "OOMKilledContainer",
    severity: "critical",
    namespace: "search",
    service: "indexer",
    is_flapping: true,
    flap_score: 6.1,
    labels: {
      alertname: "OOMKilledContainer",
      severity: "critical",
      namespace: "search",
      service: "indexer",
      container: "indexer",
      reason: "OOMKilled",
    },
    annotations: { summary: "Container killed for exceeding its memory limit" },
    last_seen_at: HOUR_5,
    last_state_change_at: HOUR_5,
    total_cases: 23,
    first_seen_at: DAY_8,
    rule: null,
    current_case: {
      id: "0f8fad5b-d9cb-469f-a165-708677289515",
      alert_id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d380d",
      seq: 23,
      state: "open",
      ack_state: "acked",
      started_at: HOUR_5,
      last_observed_at: HOUR_5,
      source_starts_at: HOUR_5,
      observed_skew_ms: 380,
    },
  }),
  mk({
    id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d380e",
    alert_key: "b3f1c2d4e5a6070e",
    alertname: "BlackboxProbeFailed",
    severity: "warning",
    namespace: null,
    service: "status-page",
    cluster_key: "prod-us",
    labels: {
      alertname: "BlackboxProbeFailed",
      severity: "warning",
      service: "status-page",
      target: "https://status.example.com/healthz",
    },
    annotations: { summary: "Probe has failed for 12 minutes" },
    last_seen_at: HOUR_5,
    last_state_change_at: HOUR_9,
    total_cases: 5,
    rule: null,
  }),
  mk({
    id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d380f",
    alert_key: "b3f1c2d4e5a6070f",
    alertname: "IngressControllerTLSHandshakeFailureRateElevatedOnEdgeNodes",
    severity: "warning",
    namespace: "edge",
    service: "ingress-nginx",
    labels: {
      alertname: "IngressControllerTLSHandshakeFailureRateElevatedOnEdgeNodes",
      severity: "warning",
      namespace: "edge",
      service: "ingress-nginx",
      node_pool: "edge-a",
    },
    annotations: { summary: "1.9% of handshakes failing at the edge" },
    snooze: snoozeUntil({
      id: "9d4e0a1b-8c2f-4d5e-6a7b-8c9d0e1f2a03",
      snoozed_by_label: "sam@example.com",
      snoozed_until: "2026-08-16T13:00:00.000Z",
      note: null,
    }),
    last_seen_at: HOUR_9,
    last_state_change_at: HOUR_19,
    total_cases: 9,
    rule: null,
    current_case: {
      id: "0f8fad5b-d9cb-469f-a165-708677289516",
      alert_id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d380f",
      seq: 9,
      state: "open",
      ack_state: "unacked",
      started_at: HOUR_19,
      last_observed_at: HOUR_9,
      source_starts_at: HOUR_19,
      observed_skew_ms: 460,
    },
  }),
  mk({
    id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d3810",
    alert_key: "b3f1c2d4e5a60710",
    alertname: "DeprecatedAPIVersionInUse",
    severity: "info",
    namespace: "platform",
    service: null,
    labels: {
      alertname: "DeprecatedAPIVersionInUse",
      severity: "info",
      namespace: "platform",
      api_version: "batch/v1beta1",
    },
    annotations: { summary: "batch/v1beta1 is removed in 1.32" },
    last_seen_at: HOUR_9,
    last_state_change_at: DAY_4,
    first_seen_at: DAY_16,
    total_cases: 1,
    rule: null,
    current_case: {
      id: "0f8fad5b-d9cb-469f-a165-708677289517",
      alert_id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d3810",
      seq: 1,
      state: "open",
      ack_state: "unacked",
      started_at: DAY_4,
      last_observed_at: HOUR_9,
      source_starts_at: DAY_4,
      observed_skew_ms: 95,
    },
  }),
  mk({
    id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d3811",
    alert_key: "b3f1c2d4e5a60711",
    alertname: "CheckoutLatencyP99Degraded",
    severity: "warning",
    namespace: "checkout",
    service: "checkout-api",
    state: "resolved",
    labels: {
      alertname: "CheckoutLatencyP99Degraded",
      severity: "warning",
      namespace: "checkout",
      service: "checkout-api",
      route: "/v2/cart",
    },
    annotations: { summary: "p99 recovered below 1.5s" },
    last_seen_at: HOUR_9,
    last_state_change_at: HOUR_9,
    total_cases: 4,
    rule: { id: RULE_LATENCY },
    current_case: {
      id: "0f8fad5b-d9cb-469f-a165-708677289518",
      alert_id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d3811",
      seq: 4,
      state: "closed",
      resolve_reason: "upstream",
      ack_state: "acked",
      started_at: HOUR_19,
      ended_at: HOUR_9,
      last_observed_at: HOUR_9,
      source_starts_at: HOUR_19,
      observed_skew_ms: 55,
    },
  }),
  mk({
    id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d3812",
    alert_key: "b3f1c2d4e5a60712",
    alertname: "NodeNotReady",
    severity: "critical",
    namespace: null,
    service: null,
    state: "resolved",
    cluster_key: "prod-us",
    labels: { alertname: "NodeNotReady", severity: "critical", node: "ip-10-42-3-77" },
    annotations: { summary: "Node returned to Ready after 6 minutes" },
    last_seen_at: HOUR_19,
    last_state_change_at: HOUR_19,
    total_cases: 2,
    rule: null,
    current_case: {
      id: "0f8fad5b-d9cb-469f-a165-708677289519",
      alert_id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d3812",
      seq: 2,
      state: "closed",
      resolve_reason: "upstream",
      ack_state: "acked",
      started_at: "2026-08-15T17:25:00.000Z",
      ended_at: HOUR_19,
      last_observed_at: HOUR_19,
      source_starts_at: "2026-08-15T17:25:00.000Z",
      observed_skew_ms: 20,
    },
  }),
  mk({
    id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d3813",
    alert_key: "b3f1c2d4e5a60713",
    alertname: "HighErrorRate",
    namespace: "payments",
    service: "refunds",
    state: "resolved",
    labels: {
      alertname: "HighErrorRate",
      severity: "critical",
      namespace: "payments",
      service: "refunds",
    },
    annotations: { summary: "Error rate returned below 5%" },
    last_seen_at: HOUR_19,
    last_state_change_at: HOUR_19,
    total_cases: 11,
    first_seen_at: DAY_40,
    current_case: {
      id: "0f8fad5b-d9cb-469f-a165-708677289520",
      alert_id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d3813",
      seq: 11,
      state: "closed",
      resolve_reason: "upstream",
      ack_state: "unacked",
      started_at: "2026-08-15T14:31:00.000Z",
      ended_at: HOUR_19,
      last_observed_at: HOUR_19,
      source_starts_at: "2026-08-15T14:31:00.000Z",
      observed_skew_ms: 160,
    },
  }),
  mk({
    id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d3814",
    alert_key: "b3f1c2d4e5a60714",
    alertname: "PrometheusRemoteWriteBehindByMoreThanFifteenMinutes",
    severity: "warning",
    namespace: "monitoring",
    service: "prometheus",
    state: "expired",
    labels: {
      alertname: "PrometheusRemoteWriteBehindByMoreThanFifteenMinutes",
      severity: "warning",
      namespace: "monitoring",
      service: "prometheus",
      remote: "cortex-eu",
    },
    annotations: { summary: "oto stopped hearing about this — nobody said it ended" },
    last_seen_at: DAY_2,
    last_state_change_at: DAY_2,
    total_cases: 6,
    rule: null,
    current_case: {
      id: "0f8fad5b-d9cb-469f-a165-708677289521",
      alert_id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d3814",
      seq: 6,
      state: "closed",
      resolve_reason: "timeout",
      ack_state: "unacked",
      started_at: DAY_4,
      ended_at: DAY_2,
      last_observed_at: DAY_2,
      source_starts_at: DAY_4,
      observed_skew_ms: 0,
    },
  }),
  mk({
    id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d3815",
    alert_key: "b3f1c2d4e5a60715",
    alertname: "KubePodCrashLooping",
    severity: "warning",
    namespace: "billing",
    service: "invoice-renderer",
    state: "expired",
    labels: {
      alertname: "KubePodCrashLooping",
      severity: "warning",
      namespace: "billing",
      service: "invoice-renderer",
      pod: "invoice-renderer-79bd4c5f8-7hkzp",
    },
    annotations: { summary: "Last seen restarting 2 days ago" },
    last_seen_at: DAY_2,
    last_state_change_at: DAY_2,
    total_cases: 14,
    first_seen_at: DAY_16,
    rule: { id: RULE_CRASHLOOP },
    current_case: {
      id: "0f8fad5b-d9cb-469f-a165-708677289522",
      alert_id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d3815",
      seq: 14,
      state: "closed",
      resolve_reason: "timeout",
      ack_state: "acked",
      started_at: DAY_4,
      ended_at: DAY_2,
      last_observed_at: DAY_2,
      source_starts_at: DAY_4,
      observed_skew_ms: 610,
    },
  }),
  mk({
    id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d3816",
    alert_key: "b3f1c2d4e5a60716",
    alertname: "TooManyOpenFileDescriptors",
    severity: "warning",
    namespace: "data",
    service: "kafka",
    labels: {
      alertname: "TooManyOpenFileDescriptors",
      severity: "warning",
      namespace: "data",
      service: "kafka",
      broker: "kafka-2",
    },
    annotations: { summary: "92% of the file-descriptor limit in use" },
    last_seen_at: DAY_2,
    last_state_change_at: DAY_4,
    total_cases: 3,
    rule: null,
    current_case: {
      id: "0f8fad5b-d9cb-469f-a165-708677289523",
      alert_id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d3816",
      seq: 3,
      state: "open",
      ack_state: "unacked",
      started_at: DAY_4,
      last_observed_at: DAY_2,
      source_starts_at: DAY_4,
      observed_skew_ms: 45,
    },
  }),
  mk({
    id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d3817",
    alert_key: "b3f1c2d4e5a60717",
    alertname: "BackupJobDidNotRun",
    severity: "critical",
    namespace: "data",
    service: null,
    labels: {
      alertname: "BackupJobDidNotRun",
      severity: "critical",
      namespace: "data",
      cronjob: "pg-basebackup",
    },
    annotations: { summary: "No successful backup in 36 hours" },
    last_seen_at: DAY_4,
    last_state_change_at: DAY_4,
    total_cases: 1,
    first_seen_at: DAY_4,
    rule: null,
    current_case: {
      id: "0f8fad5b-d9cb-469f-a165-708677289524",
      alert_id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d3817",
      seq: 1,
      state: "open",
      ack_state: "unacked",
      started_at: DAY_4,
      last_observed_at: DAY_4,
      source_starts_at: DAY_4,
      observed_skew_ms: 10,
    },
  }),
  mk({
    id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d3818",
    alert_key: "b3f1c2d4e5a60718",
    alertname: "ThanosCompactHalted",
    severity: "P1",
    namespace: "monitoring",
    service: "thanos-compact",
    labels: {
      alertname: "ThanosCompactHalted",
      severity: "P1",
      namespace: "monitoring",
      service: "thanos-compact",
    },
    annotations: { summary: "Compaction halted on an overlapping block" },
    last_seen_at: DAY_4,
    last_state_change_at: DAY_8,
    total_cases: 2,
    rule: null,
    current_case: {
      id: "0f8fad5b-d9cb-469f-a165-708677289525",
      alert_id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d3818",
      seq: 2,
      state: "open",
      ack_state: "acked",
      started_at: DAY_8,
      last_observed_at: DAY_4,
      source_starts_at: DAY_8,
      observed_skew_ms: 330,
    },
  }),
  mk({
    id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d3819",
    alert_key: "b3f1c2d4e5a60719",
    alertname: "SlackDeliveryDead",
    severity: "critical",
    namespace: null,
    service: null,
    state: "suppressed",
    labels: { alertname: "SlackDeliveryDead", severity: "critical", channel: "#sre-alerts" },
    annotations: { summary: "Token revoked three days ago" },
    last_seen_at: DAY_4,
    last_state_change_at: DAY_8,
    total_cases: 4,
    rule: null,
    current_case: {
      id: "0f8fad5b-d9cb-469f-a165-708677289526",
      alert_id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d3819",
      seq: 4,
      state: "open",
      ack_state: "unacked",
      started_at: DAY_8,
      last_observed_at: DAY_4,
      source_starts_at: DAY_8,
      observed_skew_ms: 270,
    },
  }),
  mk({
    id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d381a",
    alert_key: "b3f1c2d4e5a6071a",
    alertname: "HostClockSkewDetectedBetweenAlertmanagerAndPrometheusInstances",
    severity: "info",
    namespace: "monitoring",
    service: null,
    labels: {
      alertname: "HostClockSkewDetectedBetweenAlertmanagerAndPrometheusInstances",
      severity: "info",
      namespace: "monitoring",
      instance: "alertmanager-1",
    },
    annotations: { summary: "1.8s of skew, measured rather than corrected away" },
    last_seen_at: DAY_8,
    last_state_change_at: DAY_8,
    total_cases: 2,
    rule: null,
    current_case: {
      id: "0f8fad5b-d9cb-469f-a165-708677289527",
      alert_id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d381a",
      seq: 2,
      state: "open",
      ack_state: "unacked",
      started_at: DAY_8,
      last_observed_at: DAY_8,
      source_starts_at: DAY_8,
      observed_skew_ms: 1_800,
    },
  }),
  mk({
    id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d381b",
    alert_key: "b3f1c2d4e5a6071b",
    alertname: "EtcdMembersDown",
    severity: "critical",
    namespace: "kube-system",
    service: "etcd",
    state: "resolved",
    cluster_key: "staging-eu",
    labels: {
      alertname: "EtcdMembersDown",
      severity: "critical",
      namespace: "kube-system",
      service: "etcd",
    },
    annotations: { summary: "Quorum restored" },
    last_seen_at: DAY_8,
    last_state_change_at: DAY_8,
    total_cases: 3,
    rule: null,
    current_case: {
      id: "0f8fad5b-d9cb-469f-a165-708677289528",
      alert_id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d381b",
      seq: 3,
      state: "closed",
      resolve_reason: "upstream",
      ack_state: "acked",
      started_at: "2026-08-08T02:05:00.000Z",
      ended_at: DAY_8,
      last_observed_at: DAY_8,
      source_starts_at: "2026-08-08T02:05:00.000Z",
      observed_skew_ms: 25,
    },
  }),
  mk({
    id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d381c",
    alert_key: "b3f1c2d4e5a6071c",
    alertname: "FeatureFlagEvaluationErrors",
    severity: "warning",
    namespace: "platform",
    service: "flagd",
    state: "expired",
    labels: {
      alertname: "FeatureFlagEvaluationErrors",
      severity: "warning",
      namespace: "platform",
      service: "flagd",
    },
    annotations: {},
    last_seen_at: DAY_16,
    last_state_change_at: DAY_16,
    total_cases: 5,
    first_seen_at: DAY_40,
    rule: null,
    current_case: {
      id: "0f8fad5b-d9cb-469f-a165-708677289529",
      alert_id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d381c",
      seq: 5,
      state: "closed",
      resolve_reason: "timeout",
      ack_state: "unacked",
      started_at: DAY_40,
      ended_at: DAY_16,
      last_observed_at: DAY_16,
      source_starts_at: DAY_40,
      observed_skew_ms: 0,
    },
  }),
  mk({
    id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d381d",
    alert_key: "b3f1c2d4e5a6071d",
    alertname: "WebhookIngestRejectedElementsAboveThreshold",
    severity: "warning",
    namespace: null,
    service: null,
    state: "resolved",
    labels: {
      alertname: "WebhookIngestRejectedElementsAboveThreshold",
      severity: "warning",
      reason: "label_too_long",
    },
    annotations: { summary: "412 elements refused in one batch" },
    last_seen_at: DAY_16,
    last_state_change_at: DAY_16,
    total_cases: 1,
    first_seen_at: DAY_16,
    rule: null,
    current_case: {
      id: "0f8fad5b-d9cb-469f-a165-708677289530",
      alert_id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d381d",
      seq: 1,
      state: "closed",
      resolve_reason: "upstream",
      ack_state: "unacked",
      started_at: "2026-07-31T14:05:00.000Z",
      ended_at: DAY_16,
      last_observed_at: DAY_16,
      source_starts_at: "2026-07-31T14:05:00.000Z",
      observed_skew_ms: 5,
    },
  }),
  mk({
    id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d381e",
    alert_key: "b3f1c2d4e5a6071e",
    alertname: "GrafanaDatasourceUnreachable",
    severity: "info",
    namespace: "monitoring",
    service: "grafana",
    state: "expired",
    cluster_key: "staging-eu",
    labels: {
      alertname: "GrafanaDatasourceUnreachable",
      severity: "info",
      namespace: "monitoring",
      service: "grafana",
    },
    annotations: {},
    last_seen_at: DAY_40,
    last_state_change_at: DAY_40,
    total_cases: 2,
    first_seen_at: DAY_95,
    rule: null,
    current_case: {
      id: "0f8fad5b-d9cb-469f-a165-708677289531",
      alert_id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d381e",
      seq: 2,
      state: "closed",
      resolve_reason: "timeout",
      ack_state: "acked",
      started_at: DAY_95,
      ended_at: DAY_40,
      last_observed_at: DAY_40,
      source_starts_at: DAY_95,
      observed_skew_ms: 0,
    },
  }),
  mk({
    id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d381f",
    alert_key: "b3f1c2d4e5a6071f",
    alertname: "LegacyBatchImporterStuckOnAPoisonMessageForAnExtendedPeriod",
    severity: null,
    namespace: null,
    service: null,
    state: "resolved",
    cluster_key: "staging-eu",
    labels: { alertname: "LegacyBatchImporterStuckOnAPoisonMessageForAnExtendedPeriod" },
    annotations: { summary: "Retired importer, kept for the archive" },
    last_seen_at: DAY_95,
    last_state_change_at: DAY_95,
    total_cases: 1,
    first_seen_at: DAY_95,
    rule: null,
    current_case: {
      id: "0f8fad5b-d9cb-469f-a165-708677289532",
      alert_id: "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d381f",
      seq: 1,
      state: "closed",
      resolve_reason: "upstream",
      ack_state: "unacked",
      started_at: "2026-05-13T07:15:00.000Z",
      ended_at: DAY_95,
      last_observed_at: DAY_95,
      source_starts_at: "2026-05-13T07:15:00.000Z",
      observed_skew_ms: 0,
    },
  }),
];

/* -------------------------------------------------------------------------- */
/* Roll-up buckets                                                            */
/* -------------------------------------------------------------------------- */

function bucket(patch: Partial<AlertRollup>): AlertRollup {
  return {
    key: "HighErrorRate",
    group_by: "alertname",
    state: "firing",
    total_count: 47,
    firing_count: 31,
    suppressed_count: 6,
    resolved_count: 8,
    expired_count: 2,
    flapping_count: 3,
    severity_counts: { critical: 31, warning: 16 },
    first_seen_at: DAY_40,
    last_seen_at: MIN_2,
    ...patch,
  };
}

/** Eight buckets on the `alertname` axis, sized the way real ones arrive. */
export const PREVIEW_ROLLUPS: readonly AlertRollup[] = [
  bucket({}),
  bucket({
    key: "KubePodCrashLooping",
    total_count: 128,
    firing_count: 96,
    suppressed_count: 12,
    resolved_count: 14,
    expired_count: 6,
    flapping_count: 27,
    severity_counts: { warning: 118, info: 10 },
    first_seen_at: DAY_95,
    last_seen_at: MIN_9,
  }),
  bucket({
    key: "PaymentAuthorisationGatewayCircuitBreakerOpenForMoreThanFiveMinutes",
    total_count: 3,
    firing_count: 3,
    suppressed_count: 0,
    resolved_count: 0,
    expired_count: 0,
    flapping_count: 0,
    severity_counts: { critical: 3 },
    first_seen_at: DAY_2,
    last_seen_at: MIN_2,
  }),
  bucket({
    key: "CheckoutLatencyP99Degraded",
    state: "suppressed",
    total_count: 22,
    firing_count: 0,
    suppressed_count: 14,
    resolved_count: 8,
    expired_count: 0,
    flapping_count: 1,
    severity_counts: { warning: 22 },
    first_seen_at: DAY_16,
    last_seen_at: MIN_21,
  }),
  bucket({
    key: "ReplicationLagAboveThreshold",
    total_count: 9,
    firing_count: 4,
    suppressed_count: 1,
    resolved_count: 3,
    expired_count: 1,
    flapping_count: 0,
    severity_counts: { sev1: 6, P1: 3 },
    first_seen_at: DAY_8,
    last_seen_at: MIN_47,
  }),
  bucket({
    key: "CertificateExpiringSoon",
    total_count: 61,
    firing_count: 61,
    suppressed_count: 0,
    resolved_count: 0,
    expired_count: 0,
    flapping_count: 0,
    severity_counts: { info: 61 },
    first_seen_at: DAY_16,
    last_seen_at: HOUR_2,
  }),
  bucket({
    key: "PrometheusRemoteWriteBehindByMoreThanFifteenMinutes",
    state: "expired",
    total_count: 7,
    firing_count: 0,
    suppressed_count: 0,
    resolved_count: 2,
    expired_count: 5,
    flapping_count: 0,
    severity_counts: { warning: 7 },
    first_seen_at: DAY_40,
    last_seen_at: DAY_2,
  }),
  bucket({
    key: "EtcdMembersDown",
    state: "resolved",
    total_count: 4,
    firing_count: 0,
    suppressed_count: 0,
    resolved_count: 4,
    expired_count: 0,
    flapping_count: 0,
    severity_counts: { critical: 4 },
    first_seen_at: DAY_95,
    last_seen_at: DAY_8,
  }),
];

/* -------------------------------------------------------------------------- */
/* One alert, in full                                                         */
/* -------------------------------------------------------------------------- */

const DETAIL_ID = "8b1f0d38-6ae4-4f2d-9d3f-1f6b1f0d3801";
const CASE_ID = "0f8fad5b-d9cb-469f-a165-708677289501";
const GROUP_ID = "5e2b8c1d-4a6f-4b8c-9d0e-1f2a3b4c5d6e";

/**
 * The alert the detail section is drawn for: unacknowledged, critical and
 * long-named, because that is the row every part of the header has to cope with
 * at once.
 */
export const PREVIEW_DETAIL: AlertDetail = {
  id: DETAIL_ID,
  alert_key: "b3f1c2d4e5a607010f8fad5bd9cb469f",
  source_fingerprint: "9a8b7c6d5e4f3001",
  alertname: "KubernetesStatefulSetReplicasMismatchForExtendedPeriod",
  severity: "critical",
  namespace: "payments",
  service: "ledger-writer",
  cluster_key: "prod-eu",
  labels: {
    alertname: "KubernetesStatefulSetReplicasMismatchForExtendedPeriod",
    severity: "critical",
    namespace: "payments",
    service: "ledger-writer",
    statefulset: "ledger-writer",
    team: "payments",
    cluster: "prod-eu",
  },
  annotations: {
    summary: "2 of 5 replicas have been unavailable for 40 minutes",
    description:
      "The ledger-writer StatefulSet has been below its desired replica count since 11:19 UTC.\nWrites are still accepted but the write-ahead log is growing.",
    runbook_url: "https://runbooks.example.com/statefulset-replicas-mismatch",
  },
  generator_url:
    "https://prometheus.example.com/graph?g0.expr=kube_statefulset_status_replicas_ready&g0.tab=1",
  state: "firing",
  first_seen_at: DAY_16,
  last_seen_at: NOW,
  last_state_change_at: MIN_9,
  total_cases: 19,
  flap_score: 7.4,
  is_flapping: true,
  synthetic: false,
  snooze: null,
  current_case: {
    id: CASE_ID,
    alert_id: DETAIL_ID,
    group_id: GROUP_ID,
    seq: 19,
    state: "open",
    ack_state: "unacked",
    started_at: MIN_47,
    last_observed_at: NOW,
    source_starts_at: MIN_47,
    observed_skew_ms: 1_180,
  },
  enrichment_summary: [
    {
      enricher: "alert.history",
      enricher_version: 2,
      status: "ok",
      headline: "19 episodes in 16 days — 7 of them in the last 24 hours",
      computed_at: MIN_47,
    },
    {
      enricher: "runbook",
      enricher_version: 1,
      status: "ok",
      headline: "Runbook found in the rule's annotations",
      computed_at: MIN_47,
    },
    {
      enricher: "silence.match",
      enricher_version: 1,
      status: "skipped",
      headline: null,
      computed_at: MIN_47,
    },
  ],
  rule: { id: RULE_CRASHLOOP },
  source: {
    id: SOURCE_ID,
    name: "prod-eu alertmanager",
    kind: "alertmanager",
    cluster_key: "prod-eu",
    health_status: "healthy",
  },
  group: {
    id: GROUP_ID,
    group_key: "alertname=KubernetesStatefulSetReplicasMismatch,namespace=payments",
    generation: 4,
    title: "payments · KubernetesStatefulSetReplicasMismatch",
    state: "open",
  },
  delivery_summary: { total: 11, sent: 8, failed: 2, dead: 1, skipped: 3, pending: 0 },
};

/** The timeline, newest first — the order the detail screen opens in. */
export const PREVIEW_EVENTS: readonly AlertEvent[] = [
  // ⛔ A RETIRED EVENT TYPE, ON PURPOSE, AND THE INTENT IS UNCHANGED.
  // `alert_events` is retained thirteen months, so a real timeline still opens on
  // rows nothing mints any more; this row is here so the preview exercises the
  // path that renders them, summary and payload exactly as the server wrote them
  // at the time.
  //
  // ⭐ IT USED TO BE `alert.flapping_started` AND IT CANNOT BE ANY MORE. Migration
  // `00060` narrowed `ev_type_ck` to REFUSE that spelling — the flap detector had
  // gone blind under the case retention window W (ADR 0041 Amendment 1) — with no
  // backfill and after a database reset, so no row spelling it can exist and
  // `AlertEventType` no longer admits the literal. `group.member_joined` carries
  // the same case better: it was RETIRED by `00051`, when group membership became
  // derived from `alert_cases.group_id`, and its CHECK was deliberately never
  // narrowed. It is still in the enum, still in `EVENT_KINDS` — read but never
  // written — which is exactly the shape of history this row exists to render.
  {
    id: "a1000000-0000-4000-8000-000000000001",
    alert_id: DETAIL_ID,
    case_id: CASE_ID,
    type: "group.member_joined",
    occurred_at: MIN_9,
    recorded_at: MIN_9,
    actor_kind: "ingest",
    summary: "Case #19 joined generation 4 of payments · KubernetesStatefulSetReplicasMismatch",
    payload: { group_generation: 4, seq: 19 },
  },
  {
    id: "a1000000-0000-4000-8000-000000000002",
    alert_id: DETAIL_ID,
    case_id: CASE_ID,
    type: "delivery.failed",
    occurred_at: MIN_21,
    recorded_at: MIN_21,
    actor_kind: "notifier",
    summary: "Slack delivery to #sre-alerts failed — 429 rate_limited, retry in 30s",
    payload: { channel: "#sre-alerts", error_class: "rate_limited", status_code: 429 },
  },
  {
    id: "a1000000-0000-4000-8000-000000000003",
    alert_id: DETAIL_ID,
    case_id: CASE_ID,
    type: "delivery.sent",
    occurred_at: MIN_47,
    recorded_at: MIN_47,
    actor_kind: "notifier",
    summary: "Sent to #sre-alerts",
    payload: { channel: "#sre-alerts" },
  },
  {
    id: "a1000000-0000-4000-8000-000000000004",
    alert_id: DETAIL_ID,
    case_id: CASE_ID,
    type: "enrichment.completed",
    occurred_at: MIN_47,
    recorded_at: MIN_47,
    actor_kind: "enricher",
    summary: "alert.history: 19 episodes in 16 days",
    payload: { enricher: "alert.history", duration_ms: 143, from_cache: false },
  },
  {
    id: "a1000000-0000-4000-8000-000000000005",
    alert_id: DETAIL_ID,
    case_id: CASE_ID,
    type: "case.reopened",
    occurred_at: MIN_47,
    recorded_at: MIN_47,
    actor_kind: "ingest",
    summary: "Case #19 reopened — 2 instances firing",
    payload: { seq: 19, reopen_count: 2 },
  },
  {
    id: "a1000000-0000-4000-8000-000000000006",
    alert_id: DETAIL_ID,
    type: "comment.added",
    occurred_at: HOUR_2,
    recorded_at: HOUR_2,
    actor_kind: "user",
    actor_id: "priya@example.com",
    actor_label: "Priya R.",
    summary: "Priya R. commented: raising with the storage team, PVC attach is flapping",
    payload: { note: "raising with the storage team, PVC attach is flapping" },
  },
  {
    id: "a1000000-0000-4000-8000-000000000007",
    alert_id: DETAIL_ID,
    type: "case.resolved",
    occurred_at: HOUR_5,
    recorded_at: HOUR_5,
    actor_kind: "ingest",
    summary: "Case #18 resolved by the upstream",
    payload: { seq: 18, reason: "upstream_resolved" },
  },
  {
    id: "a1000000-0000-4000-8000-000000000008",
    alert_id: DETAIL_ID,
    type: "rule.snapshot_captured",
    occurred_at: DAY_8,
    recorded_at: DAY_8,
    actor_kind: "reconciler",
    summary: "Rule captured from the Prometheus API at fire time",
    payload: { rule_name: "KubePodCrashLooping", match_confidence: "probable" },
  },
  {
    id: "a1000000-0000-4000-8000-000000000009",
    alert_id: DETAIL_ID,
    type: "alert.created",
    occurred_at: DAY_16,
    recorded_at: DAY_16,
    actor_kind: "ingest",
    summary: "oto saw this identity for the first time",
    payload: {},
  },
];

export const PREVIEW_CASES: readonly Case[] = [
  {
    id: CASE_ID,
    alert_id: DETAIL_ID,
    group_id: GROUP_ID,
    seq: 19,
    state: "open",
    ack_state: "unacked",
    started_at: MIN_47,
    last_observed_at: NOW,
    source_starts_at: MIN_47,
    observed_skew_ms: 1_180,
  },
  {
    id: "0f8fad5b-d9cb-469f-a165-708677289502",
    alert_id: DETAIL_ID,
    group_id: GROUP_ID,
    seq: 18,
    state: "closed",
    resolve_reason: "upstream",
    ack_state: "acked",
    started_at: HOUR_9,
    ended_at: HOUR_5,
    last_observed_at: HOUR_5,
    source_starts_at: HOUR_9,
    observed_skew_ms: 240,
  },
  {
    id: "0f8fad5b-d9cb-469f-a165-708677289503",
    alert_id: DETAIL_ID,
    seq: 17,
    state: "closed",
    resolve_reason: "timeout",
    ack_state: "unacked",
    started_at: DAY_2,
    ended_at: HOUR_19,
    last_observed_at: HOUR_19,
    source_starts_at: DAY_2,
    observed_skew_ms: 0,
  },
];

export const PREVIEW_ENRICHMENTS: readonly Enrichment[] = [
  {
    id: "e1000000-0000-4000-8000-000000000001",
    subject_kind: "case",
    subject_id: CASE_ID,
    enricher: "alert.history",
    enricher_version: 2,
    phase: 1,
    status: "ok",
    payload: { episodes_16d: 19, episodes_24h: 7, median_firing_seconds: 2_280 },
    duration_ms: 143,
    from_cache: false,
    computed_at: MIN_47,
    expires_at: "2026-08-16T12:47:00.000Z",
  },
  {
    id: "e1000000-0000-4000-8000-000000000002",
    subject_kind: "case",
    subject_id: CASE_ID,
    enricher: "runbook",
    enricher_version: 1,
    phase: 1,
    status: "ok",
    payload: { url: "https://runbooks.example.com/statefulset-replicas-mismatch", source: "annotation" },
    duration_ms: 6,
    from_cache: true,
    computed_at: MIN_47,
  },
  {
    id: "e1000000-0000-4000-8000-000000000003",
    subject_kind: "case",
    subject_id: CASE_ID,
    enricher: "silence.match",
    enricher_version: 1,
    phase: 2,
    status: "timeout",
    payload: {},
    warnings: ["Alertmanager did not answer within 2s"],
    error: "context deadline exceeded after 2000ms",
    duration_ms: 2_000,
    from_cache: false,
    computed_at: MIN_47,
  },
];

export const PREVIEW_SNOOZE_HISTORY: readonly SnoozeHistoryEntry[] = [
  {
    id: "9d4e0a1b-8c2f-4d5e-6a7b-8c9d0e1f2a11",
    snoozed_at: HOUR_9,
    snoozed_until: HOUR_5,
    snoozed_by_label: "priya@example.com",
    note: "storage maintenance window",
    ended_at: HOUR_5,
    ended_reason: "expired",
    ended_by_label: null,
    active: false,
  },
  {
    id: "9d4e0a1b-8c2f-4d5e-6a7b-8c9d0e1f2a12",
    snoozed_at: DAY_2,
    snoozed_until: "2026-08-14T15:12:00.000Z",
    snoozed_by_label: "sam@example.com",
    note: null,
    ended_at: "2026-08-14T10:40:00.000Z",
    ended_reason: "manual",
    ended_by_label: "priya@example.com",
    active: false,
  },
];

export const PREVIEW_NOTIFICATIONS: readonly Notification[] = [
  {
    id: "n1000000-0000-4000-8000-000000000001",
    subject_kind: "alert_group",
    subject_id: GROUP_ID,
    group_id: GROUP_ID,
    alert_id: DETAIL_ID,
    case_id: CASE_ID,
    reason: "refired",
    policy_id: "5a1b7d8e-6f9c-4a1b-2d3e-4f5061728394",
    state_version: 9,
    status: "partial",
    delivery_summary: { total: 3, sent: 2, failed: 1, dead: 0, skipped: 0, pending: 0 },
    created_at: MIN_47,
    updated_at: MIN_21,
  },
  {
    id: "n1000000-0000-4000-8000-000000000002",
    subject_kind: "alert_group",
    subject_id: GROUP_ID,
    group_id: GROUP_ID,
    alert_id: DETAIL_ID,
    reason: "fired",
    policy_id: "5a1b7d8e-6f9c-4a1b-2d3e-4f5061728394",
    state_version: 8,
    status: "delivered",
    delivery_summary: { total: 3, sent: 3, failed: 0, dead: 0, skipped: 1, pending: 0 },
    created_at: HOUR_9,
    updated_at: HOUR_9,
  },
  {
    id: "n1000000-0000-4000-8000-000000000003",
    subject_kind: "alert_group",
    subject_id: GROUP_ID,
    group_id: GROUP_ID,
    alert_id: DETAIL_ID,
    reason: "snoozed",
    policy_id: null,
    state_version: 7,
    status: "suppressed",
    suppressed_reason: "snoozed",
    delivery_summary: { total: 0, sent: 0, failed: 0, dead: 0, skipped: 0, pending: 0 },
    created_at: HOUR_19,
    updated_at: null,
  },
];

export const PREVIEW_RULE_HISTORY: RuleHistory = {
  rule_key: {
    source_id: SOURCE_ID,
    rule_file: "/etc/prometheus/rules/kubernetes.yaml",
    rule_group: "kubernetes-apps",
    rule_name: "KubePodCrashLooping",
  },
  current: PREVIEW_RULE_SNAPSHOTS.get(RULE_CRASHLOOP) ?? null,
  change: null,
  versions: [
    PREVIEW_RULE_SNAPSHOTS.get(RULE_CRASHLOOP) ?? snapshot({}),
    snapshot({
      id: "1c9d3f4a-2b5e-4c7d-8e9f-0a1b2c3d4e04",
      rule_fingerprint: "sha256:8de1f04a3b6c9721",
      rule_file: "/etc/prometheus/rules/kubernetes.yaml",
      rule_group: "kubernetes-apps",
      rule_name: "KubePodCrashLooping",
      expr: "increase(kube_pod_container_status_restarts_total[10m]) > 5",
      for_seconds: 300,
      rule_labels: { severity: "warning" },
      captured_at: DAY_95,
    }),
  ],
};

/* -------------------------------------------------------------------------- */
/* Reference data the filter panel reads                                      */
/* -------------------------------------------------------------------------- */

export const PREVIEW_CLUSTERS: readonly Cluster[] = [
  {
    id: "3e9f5b6c-4d7a-4e9f-0b1c-2d3e4f506101",
    cluster_key: "prod-eu",
    display_name: "Production (EU)",
    source_count: 2,
    created_at: DAY_95,
    updated_at: DAY_40,
  },
  {
    id: "3e9f5b6c-4d7a-4e9f-0b1c-2d3e4f506102",
    cluster_key: "prod-us",
    display_name: "Production (US)",
    source_count: 1,
    created_at: DAY_95,
    updated_at: DAY_40,
  },
  {
    id: "3e9f5b6c-4d7a-4e9f-0b1c-2d3e4f506103",
    cluster_key: "staging-eu",
    display_name: "Staging (EU)",
    source_count: 1,
    created_at: DAY_95,
    updated_at: DAY_16,
  },
];

export const PREVIEW_LABEL_NAMES: readonly LabelNameRow[] = [
  { name: "alertname", alert_count: 1_420, promoted: true },
  { name: "severity", alert_count: 1_402, promoted: true },
  { name: "namespace", alert_count: 1_180, promoted: true },
  { name: "service", alert_count: 964, promoted: true },
  { name: "cluster", alert_count: 1_420, promoted: true },
  { name: "pod", alert_count: 731, promoted: false },
  { name: "team", alert_count: 512, promoted: false },
  { name: "container", alert_count: 388, promoted: false },
  { name: "instance", alert_count: 274, promoted: false },
  { name: "route", alert_count: 96, promoted: false },
];
