// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import starlightThemeBlack from 'starlight-theme-black';

// https://astro.build/config
export default defineConfig({
	integrations: [
		starlight({
			title: 'oto',
			description: 'The alert history layer your Prometheus stack does not have.',
			social: [{ icon: 'github', label: 'GitHub', href: 'https://github.com/thulasi-ram/oto' }],
			plugins: [starlightThemeBlack({})],
			customCss: ['./src/styles/custom.css'],
			// Overview is hand-ordered: a reader arrives knowing nothing, so the
			// order is what oto is, what its words mean, how it is built, and how
			// to change it. The four groups below are autogenerated from the
			// mirrored directories, so a new ADR or runbook needs no edit here.
			//
			// `orchestration` is deliberately absent. docs/ORCHESTRATION.md is an
			// internal build log kept as a historical record, not documentation
			// anyone should be navigated into; it is still synced, so its route and
			// every inbound link to it keep working.
			sidebar: [
				{
					label: 'Overview',
					items: [
						{ label: 'Introduction', slug: 'guides/overview' },
						{ label: 'Concepts', slug: 'concepts' },
						{ label: 'Architecture', slug: 'architecture' },
						{ label: 'Contributing', slug: 'contributing' },
						{ label: 'Releasing', slug: 'releasing' },
					],
				},
				{ label: 'Design', items: [{ autogenerate: { directory: 'design' } }] },
				{ label: 'ADRs', items: [{ autogenerate: { directory: 'adr' } }] },
				{ label: 'Setup', items: [{ autogenerate: { directory: 'setup' } }] },
				{ label: 'Runbooks', items: [{ autogenerate: { directory: 'runbooks' } }] },
			],
		}),
	],
});
