/**
 * The glyph alphabet for the alert screens — SPEC §0.3.
 *
 * ⭐ SHAPE ENCODES WHAT THE DATA ACTUALLY IS. There are two kinds of fact on an
 * alert row and they get two different visual variables:
 *
 *   - **Severity is ORDERED**, so it gets an ordered variable: the WEIGHT of the
 *     ensō's brush stroke (`SeverityEnso`). More ink = worse.
 *   - **Lifecycle state is NOMINAL**, so it gets a *nominal* variable: six
 *     unrelated shapes with no progression between them (`StateGlyph`).
 *
 * ⛔ THE PROTOTYPE'S MONOTONIC CIRCLE-FILL RAMP IS NOT PORTED. A ramp asserts an
 * order, and alert state has none: `suppressed` is orthogonal to `firing` (a
 * suppressed alert is still firing, we are simply not delivering it), `expired`
 * is terminal-by-timeout rather than terminal-by-fix, and `acked` is a human
 * annotation laid *on top of* a state rather than a step past it. Drawn as a
 * half-filled disc, "suppressed" reads "half resolved" — which is the single
 * most dangerous sentence this UI could say at 3am. So no two marks below are
 * the same shape at different fill fractions, and in particular none of the six
 * belongs to a family with more than one other member.
 *
 * Geometry is Bauhaus and uniform: a 14px box, every glyph inking the same
 * 1..13 extent so a column of them cannot appear to jitter as you scan it;
 * 1.5px strokes, butt caps, miter joins, no gradients, no corner radius.
 *
 * ⭐ THE SEVERITY MARK IS THE ONE DELIBERATE EXCEPTION TO THAT SENTENCE, and it is
 * the only glyph here that is not drawn in code. It is oto's ensō — the painted
 * brush ring from `assets/logo/oto-icon-mark.svg`, traced. A brush has no uniform
 * stroke width, no butt caps and no miter joins, which is exactly the point: a
 * generated arc with a symmetric taper is a good *drawing of* a brush stroke and
 * reads as precisely that. Everything else in this file stays geometric, because
 * everything else is a category and not the product's signature.
 *
 * Colour comes only from Tier B (`--oto-state-*` via the `*-solid` utilities),
 * because a saturated colour in oto means exactly one thing: this is the state
 * of an alert.
 */
import { Match, Switch, type Component } from "solid-js";

import { ENSO_BOX, ENSO_PATH, type EnsoWeight } from "~/components/ensoPaths";
import { cn } from "~/lib/cn";

/* -------------------------------------------------------------------------- */
/* Severity — the ensō, and the one genuinely ordinal glyph                    */
/* -------------------------------------------------------------------------- */

/**
 * ⭐⭐ SEVERITY IS DRAWN WITH oto'S OWN MARK, AT TWO BRUSH WEIGHTS.
 *
 * This was three ascending vertical bars, which was ordinal, had a constant ink
 * box, and read unmistakably as cellular reception strength. oto is not a
 * telephone, and the one glyph in the product that should look hand-made was the
 * most generic thing on the screen.
 *
 * The paths come from `~/components/ensoPaths`, generated by `just enso-trace`
 * from the painting embedded in `assets/logo/oto-icon-mark.svg`.
 * `tools/ensotrace/ensotrace.py` carries the full argument; the parts that matter
 * to a reader here are these three:
 *
 * ⭐ TWO WEIGHTS, NOT FOUR, AND THE ALLOCATION IS THE DESIGN. A three-rung weight
 * ramp does not survive 14 px, and it fails informatively: a brush carrying less
 * ink does not merely draw thinner, it SKIPS, so the light rung's dry breaks — the
 * most convincing thing about it at 40 px — fragment into disconnected specks at
 * glyph size and read as a rendering fault rather than as a light ring. So the
 * shape budget goes to the ONE boundary that pages somebody: `heavy` is
 * `critical`, `regular` is everything else. "Is this the one that wakes me" is
 * then answered by silhouette, which holds at 14 px, in greyscale, and past a
 * colour-vision deficiency.
 *
 * ⭐ `info` VERSUS `warning` IS LEFT TO HUE ALONE, and that is defensible exactly
 * here and nowhere else. The pair is oto's info blue against its warning amber —
 * the BLUE-YELLOW axis, the one that survives protanopia and deuteranopia. The
 * pair colour genuinely cannot carry is critical-against-warning (red against
 * amber), and that is the pair now carrying shape. Each channel is doing the job
 * it is strong at, rather than one ramp carrying three distinctions badly. U1 is
 * still satisfied because `SeverityMark` always ships the WORD alongside — visibly
 * when asked for, and to assistive tech always.
 *
 * ⛔ SO A THIRD WEIGHT IS NOT AN IMPROVEMENT WAITING TO BE MADE. It is the thing
 * that was tried and removed, and re-adding one puts the dry-brush speckle back.
 *
 * ⚠️ ONE OPEN QUESTION, STATED RATHER THAN LOST. At 14 px the weight difference is
 * legible but not generous; it is comfortable from about 18 px and clean at 22 px.
 * The mark is 14 px only because every glyph in this file is, and severity is the
 * axis this product is about — so `SeverityMark`'s size is worth revisiting on its
 * own merits, which is a decision about row height and not about this glyph.
 */
const ENSO_WEIGHT_AT: readonly EnsoWeight[] = ["regular", "regular", "regular", "heavy"];

/**
 * Level 0 draws the regular stroke faint rather than drawing nothing.
 *
 * The ink bounding box is then identical for every severity, so a column reads as
 * one mark at different weights instead of a mark that sometimes is not there —
 * and "unknown" stays a different statement from "info", which is what a free
 * severity vocabulary requires. It is the same bargain the unfilled bars made.
 */
const UNKNOWN_OPACITY = 0.3;

export interface SeverityEnsoProps {
  /**
   * `0` unknown … `3` critical. Anything outside the common three ranks 0 and
   * draws the faint ring: the mark is present, the reading is absent, and an
   * unrecognised severity is never coerced into a level it was not given.
   */
  readonly level: number;
  /** Accessible name. Omit when adjacent text already says it — then the glyph is hidden. */
  readonly label?: string;
  readonly class?: string;
}

export const SeverityEnso: Component<SeverityEnsoProps> = (props) => {
  const weight = (): EnsoWeight => ENSO_WEIGHT_AT[props.level] ?? "regular";
  return (
    <svg
      viewBox={`0 0 ${ENSO_BOX} ${ENSO_BOX}`}
      class={cn("size-3.5 shrink-0", props.class)}
      role={props.label === undefined ? undefined : "img"}
      aria-label={props.label}
      aria-hidden={props.label === undefined ? "true" : undefined}
    >
      <path
        d={ENSO_PATH[weight()]}
        fill="currentColor"
        opacity={props.level <= 0 ? UNKNOWN_OPACITY : 1}
      />
    </svg>
  );
};

/* -------------------------------------------------------------------------- */
/* State — six shapes, no ramp                                                */
/* -------------------------------------------------------------------------- */

/**
 * The six marks the alert screens can draw. This is deliberately wider than the
 * `State` enum: `acked` is an annotation and `info` a derived-signal tone, and
 * both need a mark from the same alphabet so the row reads as one system.
 */
export type GlyphState = "firing" | "acked" | "suppressed" | "resolved" | "expired" | "info";

/** Tier B, and only Tier B. Never a raw hex, never a foreign palette. */
const GLYPH_COLOUR: Record<GlyphState, string> = {
  firing: "text-firing-solid",
  acked: "text-acked-solid",
  suppressed: "text-suppressed-solid",
  resolved: "text-resolved-solid",
  expired: "text-expired-solid",
  info: "text-info-solid",
};

const STROKE = 1.5;

/**
 * Apex-up triangle, x 1..13 — the one unstable shape, and genuinely the
 * loudest: 72px² of ink, ahead of every other mark (resolved's hexagon below
 * included, at 52px²). The state a reader least needs to notice must never
 * outweigh the state that means "look now".
 */
const FIRING_TRIANGLE = "M7 1 L13 13 L1 13 Z";

/** An open check: no enclosing form, because an ack annotates rather than contains. */
const ACKED_CHECK = "M2 7.3 L5.6 10.9 L12 3.5";

/** Slash across the muted square, corner to corner inside its stroke. */
const SUPPRESSED_SLASH = "M3.2 10.8 L10.8 3.2";

/**
 * Circumference at r=5.25 is 2π·5.25 ≈ 32.99, so a 1.65/1.65 dash lays exactly
 * ten even ticks with no seam where the path closes: a signal arriving in gaps,
 * then not at all.
 */
const EXPIRED_DASH = "1.65 1.65";

/**
 * Resolved — a filled hexagon, deliberately outside the circle family so it
 * can never pair with expired's ring as "one shape, two fill levels". Six
 * straight sides read as a sealed, closed-case badge rather than a step on
 * any scale. Vertices (7,2.5) (11,5) (11,9) (7,11.5) (3,9) (3,5) shoelace out
 * to 52px² — comfortably under the firing triangle's 72px², so the state you
 * least need to notice is no longer the loudest mark in the column.
 */
const RESOLVED_HEXAGON = "M7 2.5 L11 5 L11 9 L7 11.5 L3 9 L3 5 Z";

export interface StateGlyphProps {
  readonly state: GlyphState;
  /**
   * `solid` paints the Tier B `*-solid` token; `inherit` takes the surrounding
   * `currentColor`, which is what a chip wants — the chip's own `*-text` token
   * is already contrast-checked against its fill.
   */
  readonly tone?: "solid" | "inherit";
  /** Accessible name. Omit when adjacent text already says it — then the glyph is hidden. */
  readonly label?: string;
  readonly class?: string;
}

export const StateGlyph: Component<StateGlyphProps> = (props) => (
  <svg
    viewBox="0 0 14 14"
    class={cn(
      "size-3.5 shrink-0",
      props.tone === "inherit" ? "" : GLYPH_COLOUR[props.state],
      props.class,
    )}
    fill="none"
    stroke-linecap="butt"
    stroke-linejoin="miter"
    role={props.label === undefined ? undefined : "img"}
    aria-label={props.label}
    aria-hidden={props.label === undefined ? "true" : undefined}
  >
    <Switch>
      {/* Firing — a filled triangle. Unstable, apex-up, maximum ink. */}
      <Match when={props.state === "firing"}>
        <path d={FIRING_TRIANGLE} fill="currentColor" />
      </Match>

      {/* Acked — a bare check. A human mark, not a container. */}
      <Match when={props.state === "acked"}>
        <path d={ACKED_CHECK} stroke="currentColor" stroke-width={STROKE} />
      </Match>

      {/* Suppressed — an outlined square struck through: present, not delivered. */}
      <Match when={props.state === "suppressed"}>
        <rect
          x={1.75}
          y={1.75}
          width={10.5}
          height={10.5}
          stroke="currentColor"
          stroke-width={STROKE}
        />
        <path d={SUPPRESSED_SLASH} stroke="currentColor" stroke-width={STROKE} />
      </Match>

      {/* Resolved — a filled hexagon. Closed, settled, sealed shut — not a ring's twin. */}
      <Match when={props.state === "resolved"}>
        <path d={RESOLVED_HEXAGON} fill="currentColor" />
      </Match>

      {/* Expired — a dashed ring. The signal came in gaps, then stopped. */}
      <Match when={props.state === "expired"}>
        <circle
          cx={7}
          cy={7}
          r={5.25}
          stroke="currentColor"
          stroke-width={STROKE}
          stroke-dasharray={EXPIRED_DASH}
        />
      </Match>

      {/* Info — a small filled square. Quiet, orthogonal, deliberately minor. */}
      <Match when={props.state === "info"}>
        <rect x={4.25} y={4.25} width={5.5} height={5.5} fill="currentColor" />
      </Match>
    </Switch>
  </svg>
);

/* -------------------------------------------------------------------------- */
/* Derived signals                                                            */
/* -------------------------------------------------------------------------- */

/*
 * ⛔ THE ALPHABET HAS NO MARK FOR A DERIVED SIGNAL ANY MORE. `WaveGlyph` — a
 * square wave, deliberately outside the state alphabet because flapping is not a
 * state — had exactly one subject, and the flap detector no longer sees it: an
 * episode damped by the case retention window W appends none of the `case.*`
 * events `flap_score` counts, so `is_flapping` reads false precisely when an
 * alert oscillates (ADR 0041 Amendment 1). Nothing in the UI presents flapping
 * as a live signal, so nothing needs the mark. The path was
 * `M1 11 V3 H4.5 V11 H8 V3 H11.5 V11 H13`, on the same 1..13 box and the same
 * stroke as every glyph above, if a derived signal ever earns one again.
 */
